version: '2'
services:
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3200 -w db.json
    ports:
      - "3200:3200"
    volumes:
      - ./data:/data
    restart: always

  client:
    build:
      context: ./
    command: npm start
    depends_on:
      - json-server
    ports:
      - "3000:3000"